apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Customerservice
  template:
    metadata:
      labels:
        app: Customerservice
    spec:
      containers:
      - name: customerrepos
        image: retailbankingsystempod1.azurecr.io/customerrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: customersnconfig

---
apiVersion: v1
kind: Service
metadata:
  name: customerservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Customerservice
