apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Accountservice
  template:
    metadata:
      labels:
        app: Accountservice
    spec:
      containers:
      - name: accountrepos
        image: retailbankingsystempod1.azurecr.io/accountrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: accountconfig

---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Accountservice